---
#Configuracion del Servidor
enableLoggingRequestDetails: false
server:
  error:
    include-message: always
    include-binding-errors: always
  compression:
    enabled: true
    min-response-size: 4096
#Configuracion del log
logging:
  level:
    root: INFO
    web: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  pattern:
    dateformat: HH:mm:ss

#Suprimir el banner de Spring
spring:
  main:
    banner-mode: off
  #Configuracion de MySQL
  datasource:
    password: admin
    url: jdbc:mysql://localhost:3306/partenon_db?useSSL=true&useTimezone=true
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-wait: 280000
      max-active: 50
      max-idle: 20
      min-idle: 15
  #Aclaraciones para JPA
  jpa:
    #Lenguaje
    database: MYSQL
    #Dialecto
    database-platform: org.hibernate.dialect.MySQL5Dialect
    #Mostrar codigo SQL
    show-sql: true
    #Desactivar OpenEntityManagerInViewInterceptor (Recomendable)
    open-in-view: false
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
        format_sql: true
  #Configuracion de servlet para tamaño de la request
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  #Configuraciones de email
  mail:
    host: localhost
    port: 1025
    username: marcoslopezdev18@gmail.com
    password: scbqvqyyfvkxbqjr
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
jwt:
  secret: secret
  expired: 14400000
...


